version: '3'
services:
  server:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - "./:/code"
    links:
      - db
  db:
    image: mongo:3.0.2